### PR TITLE
Added starter files.

### PR DESCRIPTION
**Pull request by christianareas**
```
- index.html
- assets
  - css
    - style.css
  - js
    - script.js
```

### CODE REVIEW

**Review by CharlesCoxC3 — APPROVED** [review]

**Comment by christianareas** [comment]
🤔 Still can’t merge.

**Comment by CharlesCoxC3** [comment]
maybe assign me to review it?

**Comment by christianareas** [comment]
I just added you as a collaborator, which is maybe why it didn’t work. Can you accept the invitation and try again?

**Comment by CharlesCoxC3** [comment]
nice lol

**Comment by christianareas** [comment]
Progress!

**Pull request merged**
